# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSc9lRR631TY-GxZOwAe6rW8gJzYfOUx
"""

import streamlit as st
import pandas as pd
from collections import Counter
from zipfile import ZipFile
import os
import tempfile

st.set_page_config(page_title="Excel Özellik Sayacı", layout="centered")

st.title("📊 Excel Özellik Analiz Aracı")
st.write("Bu uygulama, birden fazla Excel dosyasındaki ortak 'Özellik' sütunlarını sayar ve raporlar.")

uploaded_file = st.file_uploader("📂 ZIP formatında Excel dosyaları yükle (örn: excel_dosyalar.zip)", type="zip")

if uploaded_file:
    with tempfile.TemporaryDirectory() as tmpdir:
        zip_path = os.path.join(tmpdir, "uploaded.zip")
        with open(zip_path, "wb") as f:
            f.write(uploaded_file.read())

        with ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(tmpdir)

        ozellik_counter = Counter()

        for root, dirs, files in os.walk(tmpdir):
            for file in files:
                if file.endswith(".xlsx"):
                    file_path = os.path.join(root, file)
                    try:
                        xls = pd.ExcelFile(file_path)
                        for sheet_name in xls.sheet_names:
                            try:
                                df = xls.parse(sheet_name)
                                if "Özellik" in df.columns:
                                    ozellikler = df["Özellik"].dropna().unique()
                                    ozellik_counter.update(ozellikler)
                            except Exception as e:
                                st.warning(f"{file} - {sheet_name} okunamadı: {e}")
                    except Exception as e:
                        st.warning(f"{file} okunamadı: {e}")

        if ozellik_counter:
            df_result = pd.DataFrame(ozellik_counter.items(), columns=["Özellik", "Görülme Sayısı"])
            df_result = df_result.sort_values(by="Görülme Sayısı", ascending=False)
            st.success("Analiz tamamlandı.")
            st.dataframe(df_result)

            st.download_button("📥 Excel olarak indir", df_result.to_excel(index=False), file_name="ozellik_raporu.xlsx")
        else:
            st.error("Hiçbir özellik bulunamadı. Lütfen dosyaları kontrol et.")